name: posit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - sympy
  - matplotlib
  - jupyter_core
  - ipykernel
  - ipython
  - matplotlib-inline
  - traitlets
  - pyzmq
  - tornado
  - psutil
  - pip:
      - fxpmath==0.4.9
      - propcache==0.2.1
      - pulp==2.9.0
      - pyarrow==18.1.0
      - qtorch-plus==0.2.0
      - qtorch-posit==0.1.1
      - softfloat==0.1.4.1
      - softposit==0.3.4.4
      - tabulate==0.9.0
      - tqdm==4.66.5

# After creating this environment, install iverilog separately:
# sudo apt install iverilog
